version: '3'
services:
    rstudio:
        build: .
        image: tidy_mine
        container_name: tidyverse_jp
        environment: 
            - PASSWORD=password
        ports:
            - 8787:8787
        volumes:
            - ..:/home/rstudio
        tty: true
        stdin_open: true